# Import modules
from tfne.encodings.codeepneat.modules.codeepneat_module_dense import CoDeepNEATModuleBase
from tfne.encodings.codeepneat.modules.codeepneat_module_dense import CoDeepNEATModuleDense
